Repository siristechnology/nepaltoday-api, pull requests merged in 2019-10, with the labels that each got.

#26 Adding eslint/prettier formatting config
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  .vscode/settings.json
  src/database/resolver.test.js
  src/database/resolvers.js
Labels: size/L

#27 Adding eslint/prettier formatting config
  .eslintignore
  .eslintrc.json
  .github/workflows/nodejs.yml
  .prettierignore
  .prettierrc
  .vscode/settings.json
  src/database/resolver.test.js
  src/database/resolvers.js
Labels: size/L

#31 nep-98-pull-n-articles
  .babelrc
  .vscode/settings.json
  azure-pipelines.yml
  index.js
  package.json
  src/config/category.js
  src/config/env.js
  src/config/weight.js
  src/database/__tests__/resolver.test.js
  src/database/__tests__/resolvers.getArticles.test.js
  src/database/graphqlTestCall.js
  src/database/mocks.js
  src/database/resolver.test.js
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/helper/articleHelper.js
  src/helper/articleHelper.test.js
  src/helper/connectionHelper.js
  src/helper/connectionHelper.test.js
  src/helper/twitterHelper.test.js
  src/utils/arryUtil.test.js
  yarn.lock
Labels: good to check first, size/XXL

#34 Nep 129 create mutation api
  package.json
  src/database/__tests__/resolvers.storeFcm.test.js
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/utils/arryUtil.test.js
  yarn.lock
Labels: new feature, size/L

#37 modify-sorting-algo:
  src/database/resolvers.js
  src/helper/articleHelper.js
  src/helper/articleHelper.test.js
  src/utils/arrayUtil.js
Labels: enhancement, size/M
