Repository siristechnology/nepaltoday-api, pull requests merged in 2020-04, with the labels that each got.

#67 NEP-159 included only article id in notification data
  src/jobs/NotificationTrigger/__tests__/pushNotificationSender.integration.js
  src/jobs/NotificationTrigger/notificationHelper.js
Labels: size/XS

#68 Corona stats
  .env.sample
  index.js
  src/config/logger.js
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/db-service/coronaDbService.js
  src/db-service/database/mongooseSchema.js
  src/db-service/index.js
  src/db-service/tests/coronaDbService-getLatestStats.test.js
  src/db-service/tests/coronaDbService-saveStats.integration.js
  src/db-service/tests/coronaDbService-saveStats.test.js
  src/db-service/tests/test-db-server.js
  src/jobs/corona/index.js
  src/jobs/corona/test/corona-stats-response.json
  src/jobs/corona/test/corona.integration.js
  src/jobs/corona/test/corona.test.js
  src/jobs/job-runner/start-jobs.js
Labels: size/XXL

#70 Use ip to location and location to weather
  .env.sample
  package.json
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/server.js
  src/weather/index.js
  src/weather/test/getWeather.integration.js
  yarn.lock
Labels: size/XL
