Repository siristechnology/nepaltoday-api, pull requests merged in 2020-10, with the labels that each got.

#153 word pos library replaced fixed number of nouns
  package.json
  src/config/nouns.js
  src/jobs/NewsCrawlerTrigger/helper.js
  src/jobs/NewsCrawlerTrigger/index.js
  yarn.lock
Labels: size/M

#154 minor console erorr corrected
  src/jobs/NewsCrawlerTrigger/index.js
Labels: size/XS

#156 test
  src/jobs/NewsCrawlerTrigger/index.js
Labels: size/XS

#157 NEP-269 : Play fm radio station on background
  src/config/fm.js
  src/database/resolvers.js
  src/database/typeDefs.graphql
Labels: size/L

#158 Test code
  src/jobs/NewsCrawlerTrigger/index.js
Labels: size/XS

#159 Test code
  package.json
  yarn.lock
Labels: size/XS

#160 package name slightly changed
  package.json
Labels: size/XS

#161 Tesst one
  package.json
  yarn.lock
Labels: size/XS

#163 adding province name to fm list
  src/config/fm.js
  src/database/typeDefs.graphql
Labels: size/M

#164 NEP-273 : province add
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/db-service/database/mongooseSchema.js
Labels: size/M

#165 NEP-278 : New cases added to graphql schema
  src/database/typeDefs.graphql
  src/jobs/districtCorona/metricsJob.js
  src/jobs/districtCorona/tests/districtCorona.test.js
Labels: size/XS

#151 Testing memory in docker
  .dockerignore
  .env.defaults
  Dockerfile
  heroku.yml
Labels: size/M

#166 test
  .dockerignore
  .env.defaults
  Dockerfile
  heroku.yml
Labels: size/M

#167 new cases adding
  src/jobs/districtCorona/tests/districtCorona.test.js
Labels: size/S

#168 NEP-273 : Removing fav radio added
  src/database/resolvers.js
  src/database/typeDefs.graphql
Labels: size/S

#169 NEP-273 : Fix duplicate fav issue
  src/database/resolvers.js
Labels: size/S

#170 Nep 4 read article track
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/db-service/database/mongooseSchema.js
Labels: size/M

#171 corona notification time fixed
  src/jobs/NotificationTrigger/notificationTime.js
Labels: size/XS

#172 NEP-282 : Duplicate notification error fixed
  src/jobs/NotificationTrigger/notificationTime.js
Labels: size/XS
