Repository siristechnology/nepaltoday-api, pull requests merged in 2020-03, with the labels that each got.

#59 added newer version of express
  index.js
  package.json
  yarn.lock
Labels: size/XS

#61 added tests and fixed issue while saving notification
  src/db-service/NotificationDbService.js
  src/db-service/notificationDbService.integration.js
Labels: size/M

#63 added remove slash helper
  src/jobs/NewsCrawlerTrigger/index.js
  src/utils/arrayUtil.js
  src/utils/arryUtil.test.js
Labels: size/M

#65 populate source for latest news
  src/db-service/newsDbService.js
  yarn.lock
Labels: size/S

#66 NEP-159 added graphql query for single article
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/jobs/NotificationTrigger/__tests__/pushNotificationSender.integration.js
  src/jobs/NotificationTrigger/pushNotificationSender.js
Labels: size/S
