Repository siristechnology/nepaltoday-api, pull requests merged in 2020-09, with the labels that each got.

#103 Single news source file
  src/config/news-source-config.json
  src/config/source-data.js
  src/config/url.js
  src/config/weight.js
  src/database/__tests__/resolvers.getArticles.test.js
  src/database/mocks.js
  src/database/resolvers.js
  src/db-service/newsDbService.js
  src/helper/articleHelper.js
  src/helper/articleHelper.test.js
  src/jobs/NewsCrawlerTrigger/__tests__/NewsCrawlerTrigger.integration.js
  src/jobs/NewsCrawlerTrigger/__tests__/news-crawler.test.js
  src/jobs/NewsCrawlerTrigger/config/selector.js
  src/jobs/NewsCrawlerTrigger/index.js
  src/jobs/job-runner/start-jobs.js
Labels: DO NOT MERGE, size/XL

#104 Trending merge
  src/config/twitter-handles.js
  src/database/resolvers.js
  src/database/typeDefs.graphql
  src/db-service/database/mongooseSchema.js
  src/jobs/corona/index.js
Labels: size/M

#105 Source added
  src/config/news-source-config.json
  src/config/twitter-handles.js
  src/database/resolvers.js
  src/jobs/NewsCrawlerTrigger/index.js
  src/jobs/facebookPost/index.js
Labels: size/L

#109 twiter handle added
  src/config/twitter-handles.js
  src/db-service/database/mongooseSchema.js
Labels: size/L

#110 NEP-228 : facebook link added
  src/jobs/facebookPost/index.js
Labels: size/S

#112 fb time increased
  src/jobs/facebookPost/index.js
Labels: size/XS

#113 Article sorting added, twitter handle sport merged to other celebrity…
  src/config/twitter-handles.js
  src/database/resolvers.js
  src/jobs/facebookPost/index.js
Labels: size/M

#114 NEP-227 : article title repitition added
  package.json
  src/jobs/NewsCrawlerTrigger/helper.js
  src/jobs/NewsCrawlerTrigger/index.js
  src/jobs/facebookPost/index.js
  src/server.js
  yarn.lock
Labels: size/L

#115 ..
  src/jobs/facebookPost/index.js
Labels: size/XS

#117 Test only
  src/server.js
Labels: size/S

#118 NEP-220 : Facebook post check
  src/db-service/database/mongooseSchema.js
  src/db-service/newsDbService.js
  src/jobs/facebookPost/index.js
Labels: size/L

#119 NEP-224 : Trending topic
  src/config/news-source-config.json
  src/config/twitter-handles.js
  src/db-service/database/mongooseSchema.js
  src/db-service/trendingTopicDbService.js
  src/jobs/job-runner/start-jobs.js
  src/jobs/trendingTopics/index.js
Labels: size/M

#121 NEP-227 : New articles checked with other new articles as well as old articles since last 12 hours
  src/db-service/database/mongooseSchema.js
  src/jobs/NewsCrawlerTrigger/helper.js
  src/jobs/NewsCrawlerTrigger/index.js
Labels: size/M

#122 Twitter handle image
  src/jobs/trending/index.js
Labels: size/XS

#123 Notification duplicate error
  src/config/twitter-handles.js
  src/db-service/database/mongooseSchema.js
  src/jobs/NotificationTrigger/notificationHelper.js
Labels: size/L

#124 Twiter handle corrected
  src/config/twitter-handles.js
Labels: size/XS

#130 Source config selector
  src/config/news-source-config.json
Labels: size/XS

#131 NEP-241 : Source formatting
  src/config/news-source-config.json
Labels: size/XS

#132 NEP-232 : Previous translate check
  src/jobs/NewsCrawlerTrigger/index.js
Labels: size/S

#133 Date format corrected
  src/db-service/database/mongooseSchema.js
Labels: size/XS

#134 trending handles correcetd
  src/config/category.js
  src/config/twitter-handles.js
  src/db-service/trendingDbService.js
  src/jobs/trending/index.js
Labels: size/M

#135 fb time decreased test
  src/jobs/facebookPost/index.js
Labels: size/XS

#136 NEP-232 : hash tags added to articles
  src/database/typeDefs.graphql
  src/db-service/database/mongooseSchema.js
  src/jobs/NewsCrawlerTrigger/helper.js
  src/jobs/NewsCrawlerTrigger/index.js
Labels: size/M

#137 NEP-234 : FacebookPostWorking
  src/jobs/facebookPost/index.js
Labels: size/XS

#138 Facebook post made compatible with new library
  src/jobs/facebookPost/index.js
Labels: size/XS

#139 NEP-247 : Headline home
  src/config/category.js
  src/config/news-source-config.json
  src/jobs/NewsCrawlerTrigger/index.js
  src/jobs/trendingTopics/index.js
Labels: size/M

#140 NEP-258 : Merge समाज and बिचार category into single category समाज
  src/config/category.js
  src/config/news-source-config.json
Labels: size/S

#141 NEP-259 : Corona stats corrected and source added
  src/database/typeDefs.graphql
  src/db-service/database/mongooseSchema.js
  src/jobs/districtCorona/__tests__/districtCorona.test.js
  src/jobs/districtCorona/index.js
  src/jobs/job-runner/start-jobs.js
Labels: size/M

#142 corona job time changed to 1 hour
  src/jobs/job-runner/start-jobs.js
Labels: size/XS

#143 NEP-237 : Browser opened to show original news should have a close bu…
  src/jobs/facebookPost/index.js
  src/jobs/trendingTopics/index.js
Labels: size/L

#145 NEP-262 : trending issue solved
  src/database/typeDefs.graphql
  src/db-service/database/mongooseSchema.js
  src/db-service/trendingDbService.js
  src/jobs/job-runner/start-jobs.js
  src/jobs/trending/index.js
Labels: size/L

#147 NEP-261 : national corona summary added from other source
  package.json
  src/jobs/districtCorona/__tests__/districtCorona.test.js
  src/jobs/districtCorona/index.js
  yarn.lock
Labels: size/L

#148 created data graphql schema
  src/database/typeDefs.graphql
  src/db-service/database/mongooseSchema.js
Labels: size/XS

#149 NEP-271 : trending images size increased
  src/jobs/trending/index.js
Labels: size/XS
